String convjson ="""[
    {
        "id": 69,
        "Code": "840",
        "Ccy": "USD",
        "CcyNm_RU": "Доллар США",
        "CcyNm_UZ": "AQSH dollari",
        "CcyNm_UZC": "АҚШ доллари",
        "CcyNm_EN": "US Dollar",
        "Nominal": "1",
        "Rate": "12668.00",
        "Diff": "34.48",
        "Date": "04.04.2024"
    },
    {
        "id": 21,
        "Code": "978",
        "Ccy": "EUR",
        "CcyNm_RU": "Евро",
        "CcyNm_UZ": "EVRO",
        "CcyNm_UZC": "EВРО",
        "CcyNm_EN": "Euro",
        "Nominal": "1",
        "Rate": "13640.90",
        "Diff": "69.97",
        "Date": "04.04.2024"
    },
    {
        "id": 57,
        "Code": "643",
        "Ccy": "RUB",
        "CcyNm_RU": "Российский рубль",
        "CcyNm_UZ": "Rossiya rubli",
        "CcyNm_UZC": "Россия рубли",
        "CcyNm_EN": "Russian Ruble",
        "Nominal": "1",
        "Rate": "137.13",
        "Diff": "0.47",
        "Date": "04.04.2024"
    },
    {
        "id": 22,
        "Code": "826",
        "Ccy": "GBP",
        "CcyNm_RU": "Фунт стерлингов",
        "CcyNm_UZ": "Angliya funt sterlingi",
        "CcyNm_UZC": "Англия фунт стерлинги",
        "CcyNm_EN": "Pound Sterling",
        "Nominal": "1",
        "Rate": "15927.48",
        "Diff": "47.15",
        "Date": "04.04.2024"
    },
    {
        "id": 33,
        "Code": "392",
        "Ccy": "JPY",
        "CcyNm_RU": "Иена",
        "CcyNm_UZ": "Yaponiya iyenasi",
        "CcyNm_UZC": "Япония иенаси",
        "CcyNm_EN": "Japan Yen",
        "Nominal": "1",
        "Rate": "83.48",
        "Diff": "0.19",
        "Date": "04.04.2024"
    },
    {
        "id": 6,
        "Code": "944",
        "Ccy": "AZN",
        "CcyNm_RU": "Азербайджанский манат",
        "CcyNm_UZ": "Ozarbayjon manati",
        "CcyNm_UZC": "Озарбайжон манати",
        "CcyNm_EN": "Azerbaijan Manat",
        "Nominal": "1",
        "Rate": "7451.76",
        "Diff": "20.28",
        "Date": "04.04.2024"
    },
    {
        "id": 7,
        "Code": "050",
        "Ccy": "BDT",
        "CcyNm_RU": "Бангладешская така",
        "CcyNm_UZ": "Bangladesh takasi",
        "CcyNm_UZC": "Бангладеш такаси",
        "CcyNm_EN": "Bangladesh Taka",
        "Nominal": "1",
        "Rate": "115.43",
        "Diff": "0.32",
        "Date": "04.04.2024"
    },
    {
        "id": 8,
        "Code": "975",
        "Ccy": "BGN",
        "CcyNm_RU": "Болгарский лев",
        "CcyNm_UZ": "Bolgariya levi",
        "CcyNm_UZC": "Болгария леви",
        "CcyNm_EN": "Bulgarian Lev",
        "Nominal": "1",
        "Rate": "6974.23",
        "Diff": "36.17",
        "Date": "04.04.2024"
    },
    {
        "id": 9,
        "Code": "048",
        "Ccy": "BHD",
        "CcyNm_RU": "Бахрейнский динар",
        "CcyNm_UZ": "Bahrayn dinori",
        "CcyNm_UZC": "Баҳрайн динори",
        "CcyNm_EN": "Bahraini Dinar",
        "Nominal": "1",
        "Rate": "33602.12",
        "Diff": "91.46",
        "Date": "04.04.2024"
    },
    {
        "id": 10,
        "Code": "096",
        "Ccy": "BND",
        "CcyNm_RU": "Брунейский доллар",
        "CcyNm_UZ": "Bruney dollari",
        "CcyNm_UZC": "Бруней доллари",
        "CcyNm_EN": "Brunei Dollar",
        "Nominal": "1",
        "Rate": "9368.44",
        "Diff": "26.19",
        "Date": "04.04.2024"
    },
    {
        "id": 11,
        "Code": "986",
        "Ccy": "BRL",
        "CcyNm_RU": "Бразильский реал",
        "CcyNm_UZ": "Braziliya reali",
        "CcyNm_UZC": "Бразилия реали",
        "CcyNm_EN": "Brazilian Real",
        "Nominal": "1",
        "Rate": "2500.39",
        "Diff": "1.23",
        "Date": "04.04.2024"
    },
    {
        "id": 12,
        "Code": "933",
        "Ccy": "BYN",
        "CcyNm_RU": "Белорусский рубль",
        "CcyNm_UZ": "Belorus rubli",
        "CcyNm_UZC": "Белорус рубли",
        "CcyNm_EN": "Belarusian Ruble",
        "Nominal": "1",
        "Rate": "3870.93",
        "Diff": "10.54",
        "Date": "04.04.2024"
    },
    {
        "id": 13,
        "Code": "124",
        "Ccy": "CAD",
        "CcyNm_RU": "Канадский доллар",
        "CcyNm_UZ": "Kanada dollari",
        "CcyNm_UZC": "Канада доллари",
        "CcyNm_EN": "Canadian Dollar",
        "Nominal": "1",
        "Rate": "9331.86",
        "Diff": "16.48",
        "Date": "04.04.2024"
    },
    {
        "id": 14,
        "Code": "756",
        "Ccy": "CHF",
        "CcyNm_RU": "Швейцарский франк",
        "CcyNm_UZ": "Shveytsariya franki",
        "CcyNm_UZC": "Швейцария франки",
        "CcyNm_EN": "Swiss Franc",
        "Nominal": "1",
        "Rate": "13933.13",
        "Diff": "25.69",
        "Date": "04.04.2024"
    },
    {
        "id": 15,
        "Code": "156",
        "Ccy": "CNY",
        "CcyNm_RU": "Юань ренминби",
        "CcyNm_UZ": "Xitoy yuani",
        "CcyNm_UZC": "Хитой юани",
        "CcyNm_EN": "Yuan Renminbi",
        "Nominal": "1",
        "Rate": "1750.74",
        "Diff": "4.79",
        "Date": "04.04.2024"
    },
    {
        "id": 16,
        "Code": "192",
        "Ccy": "CUP",
        "CcyNm_RU": "Кубинское песо",
        "CcyNm_UZ": "Kuba pesosi",
        "CcyNm_UZC": "Куба песоси",
        "CcyNm_EN": "Cuban Peso",
        "Nominal": "1",
        "Rate": "527.83",
        "Diff": "1.43",
        "Date": "04.04.2024"
    },
    {
        "id": 17,
        "Code": "203",
        "Ccy": "CZK",
        "CcyNm_RU": "Чешская крона",
        "CcyNm_UZ": "Chexiya kronasi",
        "CcyNm_UZC": "Чехия кронаси",
        "CcyNm_EN": "Czech Koruna",
        "Nominal": "1",
        "Rate": "538.81",
        "Diff": "3.4",
        "Date": "04.04.2024"
    },
    {
        "id": 18,
        "Code": "208",
        "Ccy": "DKK",
        "CcyNm_RU": "Датская крона",
        "CcyNm_UZ": "Daniya kronasi",
        "CcyNm_UZC": "Дания кронаси",
        "CcyNm_EN": "Danish Krone",
        "Nominal": "1",
        "Rate": "1828.84",
        "Diff": "9.34",
        "Date": "04.04.2024"
    },
    {
        "id": 19,
        "Code": "012",
        "Ccy": "DZD",
        "CcyNm_RU": "Алжирский динар",
        "CcyNm_UZ": "Jazoir dinori",
        "CcyNm_UZC": "Жазоир динори",
        "CcyNm_EN": "Algerian Dinar",
        "Nominal": "1",
        "Rate": "93.99",
        "Diff": "0.27",
        "Date": "04.04.2024"
    },
    {
        "id": 20,
        "Code": "818",
        "Ccy": "EGP",
        "CcyNm_RU": "Египетский фунт",
        "CcyNm_UZ": "Misr funti",
        "CcyNm_UZC": "Миср фунти",
        "CcyNm_EN": "Egyptian Pound",
        "Nominal": "1",
        "Rate": "266.25",
        "Diff": "-1.72",
        "Date": "04.04.2024"
    },
    {
        "id": 2,
        "Code": "971",
        "Ccy": "AFN",
        "CcyNm_RU": "Афгани",
        "CcyNm_UZ": "Afg‘oniston afg‘onisi",
        "CcyNm_UZC": "Афғонистон афғониси",
        "CcyNm_EN": "AF Afghani",
        "Nominal": "1",
        "Rate": "178.02",
        "Diff": "0.48",
        "Date": "04.04.2024"
    },
    {
        "id": 4,
        "Code": "032",
        "Ccy": "ARS",
        "CcyNm_RU": "Аргентинское песо",
        "CcyNm_UZ": "Argentina pesosi",
        "CcyNm_UZC": "Аргентина песоси",
        "CcyNm_EN": "Argentine Peso",
        "Nominal": "1",
        "Rate": "14.77",
        "Diff": "0.04",
        "Date": "04.04.2024"
    },
    {
        "id": 23,
        "Code": "981",
        "Ccy": "GEL",
        "CcyNm_RU": "Грузинский лари",
        "CcyNm_UZ": "Gruziya larisi",
        "CcyNm_UZC": "Грузия лариси",
        "CcyNm_EN": "Georgian Lari",
        "Nominal": "1",
        "Rate": "4721.58",
        "Diff": "4.06",
        "Date": "04.04.2024"
    },
    {
        "id": 24,
        "Code": "344",
        "Ccy": "HKD",
        "CcyNm_RU": "Гонгконгский доллар",
        "CcyNm_UZ": "Gongkong dollari",
        "CcyNm_UZC": "Гонгконг доллари",
        "CcyNm_EN": "Hong Kong Dollar",
        "Nominal": "1",
        "Rate": "1618.13",
        "Diff": "4.32",
        "Date": "04.04.2024"
    },
    {
        "id": 25,
        "Code": "348",
        "Ccy": "HUF",
        "CcyNm_RU": "Венгерский форинт",
        "CcyNm_UZ": "Vengriya forinti",
        "CcyNm_UZC": "Венгрия форинти",
        "CcyNm_EN": "Hungarian Forint",
        "Nominal": "1",
        "Rate": "34.66",
        "Diff": "0.28",
        "Date": "04.04.2024"
    },
    {
        "id": 26,
        "Code": "360",
        "Ccy": "IDR",
        "CcyNm_RU": "Рупия",
        "CcyNm_UZ": "Indoneziya rupiyasi",
        "CcyNm_UZC": "Индонезия рупияси",
        "CcyNm_EN": "Rupiah",
        "Nominal": "10",
        "Rate": "7.96",
        "Diff": "0.01",
        "Date": "04.04.2024"
    },
    {
        "id": 27,
        "Code": "376",
        "Ccy": "ILS",
        "CcyNm_RU": "Новый израильский шекель",
        "CcyNm_UZ": "Isroil shekeli",
        "CcyNm_UZC": "Исроил шекели",
        "CcyNm_EN": "New Israeli Sheqel",
        "Nominal": "1",
        "Rate": "3405.38",
        "Diff": "-11.67",
        "Date": "04.04.2024"
    },
    {
        "id": 28,
        "Code": "356",
        "Ccy": "INR",
        "CcyNm_RU": "Индийская рупия",
        "CcyNm_UZ": "Hindiston rupiyasi",
        "CcyNm_UZC": "Ҳиндистон рупияси",
        "CcyNm_EN": "Indian Rupee",
        "Nominal": "1",
        "Rate": "151.84",
        "Diff": "0.31",
        "Date": "04.04.2024"
    },
    {
        "id": 29,
        "Code": "368",
        "Ccy": "IQD",
        "CcyNm_RU": "Иракский динар",
        "CcyNm_UZ": "Iroq dinori",
        "CcyNm_UZC": "Ироқ динори",
        "CcyNm_EN": "Iraqi Dinar",
        "Nominal": "1",
        "Rate": "9.67",
        "Diff": "0.03",
        "Date": "04.04.2024"
    },
    {
        "id": 30,
        "Code": "364",
        "Ccy": "IRR",
        "CcyNm_RU": "Иранский риал",
        "CcyNm_UZ": "Eron riali",
        "CcyNm_UZC": "Эрон риали",
        "CcyNm_EN": "Iranian Rial",
        "Nominal": "10",
        "Rate": "3.02",
        "Diff": "0.01",
        "Date": "04.04.2024"
    },
    {
        "id": 31,
        "Code": "352",
        "Ccy": "ISK",
        "CcyNm_RU": "Исландская крона",
        "CcyNm_UZ": "Islandiya kronasi",
        "CcyNm_UZC": "Исландия кронаси",
        "CcyNm_EN": "Iceland Krona",
        "Nominal": "1",
        "Rate": "90.88",
        "Diff": "0.59",
        "Date": "04.04.2024"
    },
    {
        "id": 32,
        "Code": "400",
        "Ccy": "JOD",
        "CcyNm_RU": "Иорданский динар",
        "CcyNm_UZ": "Iordaniya dinori",
        "CcyNm_UZC": "Иордания динори",
        "CcyNm_EN": "Jordanian Dinar",
        "Nominal": "1",
        "Rate": "17867.42",
        "Diff": "48.63",
        "Date": "04.04.2024"
    },
    {
        "id": 5,
        "Code": "036",
        "Ccy": "AUD",
        "CcyNm_RU": "Австралийский доллар",
        "CcyNm_UZ": "Avstraliya dollari",
        "CcyNm_UZC": "Австралия доллари",
        "CcyNm_EN": "Australian Dollar",
        "Nominal": "1",
        "Rate": "8243.07",
        "Diff": "21.18",
        "Date": "04.04.2024"
    },
    {
        "id": 34,
        "Code": "417",
        "Ccy": "KGS",
        "CcyNm_RU": "Киргизский сом",
        "CcyNm_UZ": "Qirg‘iz somi",
        "CcyNm_UZC": "Қирғиз соми",
        "CcyNm_EN": "Kyrgyzstan Som",
        "Nominal": "1",
        "Rate": "141.74",
        "Diff": "0.48",
        "Date": "04.04.2024"
    },
    {
        "id": 35,
        "Code": "116",
        "Ccy": "KHR",
        "CcyNm_RU": "Риель",
        "CcyNm_UZ": "Kambodja riyeli",
        "CcyNm_UZC": "Камбоджа риели",
        "CcyNm_EN": "Riel",
        "Nominal": "1",
        "Rate": "3.13",
        "Diff": "0",
        "Date": "04.04.2024"
    },
    {
        "id": 36,
        "Code": "410",
        "Ccy": "KRW",
        "CcyNm_RU": "Вона Республики Корея",
        "CcyNm_UZ": "Koreya Respublikasi voni",
        "CcyNm_UZC": "Корея Республикаси вони",
        "CcyNm_EN": "The Korean Republic Won",
        "Nominal": "1",
        "Rate": "9.38",
        "Diff": "0.02",
        "Date": "04.04.2024"
    },
    {
        "id": 37,
        "Code": "414",
        "Ccy": "KWD",
        "CcyNm_RU": "Кувейтский динар",
        "CcyNm_UZ": "Quvayt dinori",
        "CcyNm_UZC": "Қувайт динори",
        "CcyNm_EN": "Kuwaiti Dinar",
        "Nominal": "1",
        "Rate": "41156.60",
        "Diff": "98.69",
        "Date": "04.04.2024"
    },
    {
        "id": 38,
        "Code": "398",
        "Ccy": "KZT",
        "CcyNm_RU": "Казахстанский тенге",
        "CcyNm_UZ": "Qozog‘iston tengesi",
        "CcyNm_UZC": "Қозоғистон тенгеси",
        "CcyNm_EN": "Kazakhstan Tenge",
        "Nominal": "1",
        "Rate": "28.32",
        "Diff": "0.09",
        "Date": "04.04.2024"
    },
    {
        "id": 39,
        "Code": "418",
        "Ccy": "LAK",
        "CcyNm_RU": "Лаосский кип",
        "CcyNm_UZ": "Laos kipisi",
        "CcyNm_UZC": "Лаос киписи",
        "CcyNm_EN": "Lao Kip",
        "Nominal": "1",
        "Rate": "0.60",
        "Diff": "0",
        "Date": "04.04.2024"
    },
    {
        "id": 40,
        "Code": "422",
        "Ccy": "LBP",
        "CcyNm_RU": "Ливанский фунт",
        "CcyNm_UZ": "Livan funti",
        "CcyNm_UZC": "Ливан фунти",
        "CcyNm_EN": "Lebanese Pound",
        "Nominal": "1",
        "Rate": "0.14",
        "Diff": "0",
        "Date": "04.04.2024"
    },
    {
        "id": 41,
        "Code": "434",
        "Ccy": "LYD",
        "CcyNm_RU": "Ливийский динар",
        "CcyNm_UZ": "Liviya dinori",
        "CcyNm_UZC": "Ливия динори",
        "CcyNm_EN": "Libyan Dinar",
        "Nominal": "1",
        "Rate": "2609.43",
        "Diff": "0.87",
        "Date": "04.04.2024"
    },
    {
        "id": 42,
        "Code": "504",
        "Ccy": "MAD",
        "CcyNm_RU": "Марокканский дирхам",
        "CcyNm_UZ": "Marokash dirhami",
        "CcyNm_UZC": "Марокаш дирҳами",
        "CcyNm_EN": "Moroccan Dirham",
        "Nominal": "1",
        "Rate": "1256.83",
        "Diff": "7.33",
        "Date": "04.04.2024"
    },
    {
        "id": 43,
        "Code": "498",
        "Ccy": "MDL",
        "CcyNm_RU": "Молдавский лей",
        "CcyNm_UZ": "Moldaviya leyi",
        "CcyNm_UZC": "Молдавия лейи",
        "CcyNm_EN": "Moldovan Leu",
        "Nominal": "1",
        "Rate": "713.89",
        "Diff": "1.74",
        "Date": "04.04.2024"
    },
    {
        "id": 44,
        "Code": "104",
        "Ccy": "MMK",
        "CcyNm_RU": "Мьянманский кьят",
        "CcyNm_UZ": "Myanma kyati",
        "CcyNm_UZC": "Мьянма кьяти",
        "CcyNm_EN": "Kyat",
        "Nominal": "1",
        "Rate": "6.03",
        "Diff": "0.01",
        "Date": "04.04.2024"
    },
    {
        "id": 45,
        "Code": "496",
        "Ccy": "MNT",
        "CcyNm_RU": "Монгольский тугpик",
        "CcyNm_UZ": "Mongoliya tugriki",
        "CcyNm_UZC": "Монголия тугрики",
        "CcyNm_EN": "Tugrik",
        "Nominal": "1",
        "Rate": "3.73",
        "Diff": "0.01",
        "Date": "04.04.2024"
    },
    {
        "id": 46,
        "Code": "484",
        "Ccy": "MXN",
        "CcyNm_RU": "Мексиканское песо",
        "CcyNm_UZ": "Meksika pesosi",
        "CcyNm_UZC": "Мексика песоси",
        "CcyNm_EN": "Mexican Peso",
        "Nominal": "1",
        "Rate": "764.06",
        "Diff": "2.67",
        "Date": "04.04.2024"
    },
    {
        "id": 47,
        "Code": "458",
        "Ccy": "MYR",
        "CcyNm_RU": "Малайзийский ринггит",
        "CcyNm_UZ": "Malayziya ringgiti",
        "CcyNm_UZC": "Малайзия ринггити",
        "CcyNm_EN": "Malaysian Ringgit",
        "Nominal": "1",
        "Rate": "2664.14",
        "Diff": "6.97",
        "Date": "04.04.2024"
    },
    {
        "id": 48,
        "Code": "578",
        "Ccy": "NOK",
        "CcyNm_RU": "Норвежская крона",
        "CcyNm_UZ": "Norvegiya kronasi",
        "CcyNm_UZC": "Норвегия кронаси",
        "CcyNm_EN": "Norwegian Krone",
        "Nominal": "1",
        "Rate": "1168.10",
        "Diff": "9.03",
        "Date": "04.04.2024"
    },
    {
        "id": 49,
        "Code": "554",
        "Ccy": "NZD",
        "CcyNm_RU": "Новозеландский доллар",
        "CcyNm_UZ": "Yangi Zelandiya dollari",
        "CcyNm_UZC": "Янги Зеландия доллари",
        "CcyNm_EN": "New Zealand Dollar",
        "Nominal": "1",
        "Rate": "7556.46",
        "Diff": "28.15",
        "Date": "04.04.2024"
    },
    {
        "id": 50,
        "Code": "512",
        "Ccy": "OMR",
        "CcyNm_RU": "Оманский риал",
        "CcyNm_UZ": "Ummon riali",
        "CcyNm_UZC": "Уммон риали",
        "CcyNm_EN": "Rial Omani",
        "Nominal": "1",
        "Rate": "32903.90",
        "Diff": "89.56",
        "Date": "04.04.2024"
    },
    {
        "id": 51,
        "Code": "608",
        "Ccy": "PHP",
        "CcyNm_RU": "Филиппинское песо",
        "CcyNm_UZ": "Filippin pesosi",
        "CcyNm_UZC": "Филиппин песоси",
        "CcyNm_EN": "Philippine Piso",
        "Nominal": "1",
        "Rate": "224.53",
        "Diff": "0.09",
        "Date": "04.04.2024"
    },
    {
        "id": 52,
        "Code": "586",
        "Ccy": "PKR",
        "CcyNm_RU": "Пакистанская рупия",
        "CcyNm_UZ": "Pokiston rupiyasi",
        "CcyNm_UZC": "Покистон рупияси",
        "CcyNm_EN": "Pakistan Rupee",
        "Nominal": "1",
        "Rate": "45.58",
        "Diff": "0.11",
        "Date": "04.04.2024"
    },
    {
        "id": 53,
        "Code": "985",
        "Ccy": "PLN",
        "CcyNm_RU": "Злотый",
        "CcyNm_UZ": "Polsha zlotiysi",
        "CcyNm_UZC": "Польша злотийси",
        "CcyNm_EN": "Polish Zloty",
        "Nominal": "1",
        "Rate": "3176.77",
        "Diff": "15.39",
        "Date": "04.04.2024"
    },
    {
        "id": 54,
        "Code": "634",
        "Ccy": "QAR",
        "CcyNm_RU": "Катарский риал",
        "CcyNm_UZ": "Qatar riali",
        "CcyNm_UZC": "Қатар риали",
        "CcyNm_EN": "Qatari Rial",
        "Nominal": "1",
        "Rate": "3474.02",
        "Diff": "9.46",
        "Date": "04.04.2024"
    },
    {
        "id": 55,
        "Code": "946",
        "Ccy": "RON",
        "CcyNm_RU": "Румынский лей",
        "CcyNm_UZ": "Ruminiya leyi",
        "CcyNm_UZC": "Руминия лейи",
        "CcyNm_EN": "Romanian Leu",
        "Nominal": "1",
        "Rate": "2745.26",
        "Diff": "14.87",
        "Date": "04.04.2024"
    },
    {
        "id": 56,
        "Code": "941",
        "Ccy": "RSD",
        "CcyNm_RU": "Сербский динар",
        "CcyNm_UZ": "Serbiya dinori",
        "CcyNm_UZC": "Сербия динори",
        "CcyNm_EN": "Serbian Dinar",
        "Nominal": "1",
        "Rate": "116.45",
        "Diff": "0.6",
        "Date": "04.04.2024"
    },
    {
        "id": 3,
        "Code": "051",
        "Ccy": "AMD",
        "CcyNm_RU": "Армянский драм",
        "CcyNm_UZ": "Armaniston drami",
        "CcyNm_UZC": "Арманистон драми",
        "CcyNm_EN": "Armenian Dram",
        "Nominal": "1",
        "Rate": "32.61",
        "Diff": "0.38",
        "Date": "04.04.2024"
    },
    {
        "id": 58,
        "Code": "682",
        "Ccy": "SAR",
        "CcyNm_RU": "Саудовский риял",
        "CcyNm_UZ": "Saudiya Arabistoni riali",
        "CcyNm_UZC": "Саудия Арабистони риали",
        "CcyNm_EN": "Saudi Riyal",
        "Nominal": "1",
        "Rate": "3377.32",
        "Diff": "9.1",
        "Date": "04.04.2024"
    },
    {
        "id": 59,
        "Code": "938",
        "Ccy": "SDG",
        "CcyNm_RU": "Суданский фунт",
        "CcyNm_UZ": "Sudan funti",
        "CcyNm_UZC": "Судан фунти",
        "CcyNm_EN": "Sudanese Pound",
        "Nominal": "1",
        "Rate": "21.10",
        "Diff": "0.06",
        "Date": "04.04.2024"
    },
    {
        "id": 60,
        "Code": "752",
        "Ccy": "SEK",
        "CcyNm_RU": "Шведская крона",
        "CcyNm_UZ": "Shvetsiya kronasi",
        "CcyNm_UZC": "Швеция кронаси",
        "CcyNm_EN": "Swedish Krona",
        "Nominal": "1",
        "Rate": "1178.60",
        "Diff": "5.57",
        "Date": "04.04.2024"
    },
    {
        "id": 61,
        "Code": "702",
        "Ccy": "SGD",
        "CcyNm_RU": "Сингапурский доллар",
        "CcyNm_UZ": "Singapur dollari",
        "CcyNm_UZC": "Сингапур доллари",
        "CcyNm_EN": "Singapore Dollar",
        "Nominal": "1",
        "Rate": "9368.44",
        "Diff": "26.19",
        "Date": "04.04.2024"
    },
    {
        "id": 62,
        "Code": "760",
        "Ccy": "SYP",
        "CcyNm_RU": "Сирийский фунт",
        "CcyNm_UZ": "Suriya funti",
        "CcyNm_UZC": "Сурия фунти",
        "CcyNm_EN": "Syrian Pound",
        "Nominal": "1",
        "Rate": "0.97",
        "Diff": "0",
        "Date": "04.04.2024"
    },
    {
        "id": 63,
        "Code": "764",
        "Ccy": "THB",
        "CcyNm_RU": "Бат",
        "CcyNm_UZ": "Tailand bati",
        "CcyNm_UZC": "Таиланд бати",
        "CcyNm_EN": "Baht",
        "Nominal": "1",
        "Rate": "345.18",
        "Diff": "0.33",
        "Date": "04.04.2024"
    },
    {
        "id": 64,
        "Code": "972",
        "Ccy": "TJS",
        "CcyNm_RU": "Сомони",
        "CcyNm_UZ": "Tojikiston somonisi",
        "CcyNm_UZC": "Тожикистон сомониси",
        "CcyNm_EN": "Tajikistan Somoni",
        "Nominal": "1",
        "Rate": "1155.84",
        "Diff": "2.09",
        "Date": "04.04.2024"
    },
    {
        "id": 65,
        "Code": "934",
        "Ccy": "TMT",
        "CcyNm_RU": "Новый туркменский манат",
        "CcyNm_UZ": "Turkmaniston manati",
        "CcyNm_UZC": "Туркманистон манати",
        "CcyNm_EN": "Turkmenistan New Manat",
        "Nominal": "1",
        "Rate": "3624.61",
        "Diff": "9.87",
        "Date": "04.04.2024"
    },
    {
        "id": 66,
        "Code": "788",
        "Ccy": "TND",
        "CcyNm_RU": "Тунисский динар",
        "CcyNm_UZ": "Tunis dinori",
        "CcyNm_UZC": "Тунис динори",
        "CcyNm_EN": "Tunisian Dinar",
        "Nominal": "1",
        "Rate": "4040.83",
        "Diff": "16.78",
        "Date": "04.04.2024"
    },
    {
        "id": 67,
        "Code": "949",
        "Ccy": "TRY",
        "CcyNm_RU": "Турецкая лира",
        "CcyNm_UZ": "Turkiya lirasi",
        "CcyNm_UZC": "Туркия лираси",
        "CcyNm_EN": "Turkish Lira",
        "Nominal": "1",
        "Rate": "396.07",
        "Diff": "3.76",
        "Date": "04.04.2024"
    },
    {
        "id": 68,
        "Code": "980",
        "Ccy": "UAH",
        "CcyNm_RU": "Гривна",
        "CcyNm_UZ": "Ukraina grivnasi",
        "CcyNm_UZC": "Украина гривнаси",
        "CcyNm_EN": "Ukrainian Hryvnia",
        "Nominal": "1",
        "Rate": "323.40",
        "Diff": "2.19",
        "Date": "04.04.2024"
    },
    {
        "id": 1,
        "Code": "784",
        "Ccy": "AED",
        "CcyNm_RU": "Дирхам ОАЭ",
        "CcyNm_UZ": "BAA dirhami",
        "CcyNm_UZC": "БАА дирҳами",
        "CcyNm_EN": "UAE Dirham",
        "Nominal": "1",
        "Rate": "3449.42",
        "Diff": "9.39",
        "Date": "04.04.2024"
    },
    {
        "id": 70,
        "Code": "858",
        "Ccy": "UYU",
        "CcyNm_RU": "Уругвайское песо",
        "CcyNm_UZ": "Urugvay pesosi",
        "CcyNm_UZC": "Уругвай песоси",
        "CcyNm_EN": "Peso Uruguayo",
        "Nominal": "1",
        "Rate": "334.47",
        "Diff": "-1.84",
        "Date": "04.04.2024"
    },
    {
        "id": 71,
        "Code": "928",
        "Ccy": "VES",
        "CcyNm_RU": "Венесуэльский боливар",
        "CcyNm_UZ": "Venesuela bolivari",
        "CcyNm_UZC": "Венесуэла боливари",
        "CcyNm_EN": "Bolívar",
        "Nominal": "1",
        "Rate": "349.55",
        "Diff": "0.71",
        "Date": "04.04.2024"
    },
    {
        "id": 72,
        "Code": "704",
        "Ccy": "VND",
        "CcyNm_RU": "Донг",
        "CcyNm_UZ": "Vetnam dongi",
        "CcyNm_UZC": "Вьетнам донги",
        "CcyNm_EN": "Dong",
        "Nominal": "10",
        "Rate": "5.07",
        "Diff": "0",
        "Date": "04.04.2024"
    },
    {
        "id": 73,
        "Code": "960",
        "Ccy": "XDR",
        "CcyNm_RU": "СДР",
        "CcyNm_UZ": "SDR",
        "CcyNm_UZC": "СДР",
        "CcyNm_EN": "SDR",
        "Nominal": "1",
        "Rate": "16738.75",
        "Diff": "16.02",
        "Date": "04.04.2024"
    },
    {
        "id": 74,
        "Code": "886",
        "Ccy": "YER",
        "CcyNm_RU": "Йеменский риал",
        "CcyNm_UZ": "Yaman riali",
        "CcyNm_UZC": "Яман риали",
        "CcyNm_EN": "Yemeni Rial",
        "Nominal": "1",
        "Rate": "50.60",
        "Diff": "0.11",
        "Date": "04.04.2024"
    },
    {
        "id": 75,
        "Code": "710",
        "Ccy": "ZAR",
        "CcyNm_RU": "Рэнд",
        "CcyNm_UZ": "Janubiy Afrika randi",
        "CcyNm_UZC": "Жанубий Африка ранди",
        "CcyNm_EN": "Rand",
        "Nominal": "1",
        "Rate": "673.94",
        "Diff": "2.32",
        "Date": "04.04.2024"
    }
]""";
